openapi: 3.0.3
info:
  title: Pizza Day API
  description: API для системи замовлення піци - модульний моноліт
  version: 1.0.0
  contact:
    name: Pizza Day Team
    email: dev@pizzaday.com

servers:
  - url: http://localhost:8080/api
    description: Локальний сервер розробки
  - url: https://api.pizzaday.com/v1
    description: Продакшен сервер

paths:
  /pizzas:
    get:
      summary: Отримати список всіх піц
      operationId: getPizzas
      tags:
        - Pizzas
      responses:
        '200':
          description: Успішне отримання списку піц
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PizzaResponse'
        '500':
          description: Внутрішня помилка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Створити нову піцу
      operationId: createPizza
      tags:
        - Pizzas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePizzaRequest'
      responses:
        '201':
          description: Піца успішно створена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PizzaResponse'
        '400':
          description: Помилка валідації даних
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутрішня помилка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /pizzas/{id}:
    get:
      summary: Отримати піцу по ID
      operationId: getPizzaById
      tags:
        - Pizzas
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Унікальний ідентифікатор піци
          example: "pizza-123"
      responses:
        '200':
          description: Успішне отримання піци
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PizzaResponse'
        '404':
          description: Піца не знайдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутрішня помилка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Повністю оновити піцу
      operationId: updatePizza
      tags:
        - Pizzas
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePizzaRequest'
      responses:
        '200':
          description: Піца успішно оновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PizzaResponse'
        '400':
          description: Помилка валідації даних
        '404':
          description: Піца не знайдена
        '500':
          description: Внутрішня помилка сервера

    delete:
      summary: Видалити піцу
      operationId: deletePizza
      tags:
        - Pizzas
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Піца успішно видалена
        '404':
          description: Піца не знайдена
        '500':
          description: Внутрішня помилка сервера

  /health:
    get:
      summary: Перевірка здоров'я сервісу
      operationId: healthCheck
      tags:
        - System
      responses:
        '200':
          description: Сервіс працює коректно
          content:
            text/plain:
              schema:
                type: string
                example: "ok"

components:
  schemas:
    CreatePizzaRequest:
      type: object
      required:
        - name
        - price
        - ingredients
        - size
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 100
          example: "Маргарита"
          description: Назва піци
        description:
          type: string
          maxLength: 500
          example: "Класична піца з томатами та моцарелою"
          description: Опис піци
        price:
          type: number
          format: decimal
          minimum: 50
          maximum: 1000
          example: 199.00
          description: Ціна піци
        ingredients:
          type: array
          minItems: 1
          items:
            type: string
          example: ["томатний соус", "моцарела", "базилік"]
          description: Список інгредієнтів
        size:
          type: string
          enum: [SMALL, MEDIUM, LARGE, FAMILY]
          example: "MEDIUM"
          description: Розмір піци

    UpdatePizzaRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 100
          example: "Маргарита Про"
        description:
          type: string
          maxLength: 500
          example: "Покращена версія класичної піци"
        price:
          type: number
          format: decimal
          minimum: 50
          maximum: 1000
          example: 229.00
        ingredients:
          type: array
          minItems: 1
          items:
            type: string
          example: ["томатний соус", "моцарела", "базилік", "оливкова олія"]
        size:
          type: string
          enum: [SMALL, MEDIUM, LARGE, FAMILY]
          example: "LARGE"

    PizzaResponse:
      type: object
      properties:
        id:
          type: string
          example: "pizza-123"
          description: Унікальний ідентифікатор піци
        name:
          type: string
          example: "Маргарита"
        description:
          type: string
          example: "Класична піца з томатами та моцарелою"
        price:
          type: number
          format: decimal
          example: 199.00
        ingredients:
          type: array
          items:
            type: string
          example: ["томатний соус", "моцарела", "базилік"]
        size:
          type: string
          example: "MEDIUM"
        isAvailable:
          type: boolean
          example: true
          description: Чи доступна піца для замовлення
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"

    ErrorResponse:
      type: object
      required:
        - error
        - code
        - message
      properties:
        error:
          type: string
          example: "ValidationError"
          description: Тип помилки
        code:
          type: string
          example: "NAME_REQUIRED"
          description: Код помилки для машинної обробки
        message:
          type: string
          example: "Name is required"
          description: Людинозрозуміле повідомлення про помилку
        details:
          type: array
          description: Детальна інформація про помилки валідації
          items:
            type: object
            properties:
              field:
                type: string
                example: "name"
              message:
                type: string
                example: "Name must be at least 2 characters long"
        timestamp:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        path:
          type: string
          example: "/api/pizzas"

  responses:
    NotFound:
      description: Ресурс не знайдено
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ValidationError:
      description: Помилка валідації даних
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
